version: '3'

services:
  base: &base
    build: './server'
    env_file: .env
    environment:
      POSTGRES_HOST: postgress_bd
      REDIS_HOST: redis
    volumes:
      - ./server:/work/server

  server:
    <<: *base
    command: python main.py
    ports:
      - '3000:3000'
    depends_on:
      - postgress_bd
      - redis

  lint:
    <<: *base
    command: flake8
  
  format:
    <<: *base
    command: black . --exclude=venv

  check-format:
    <<: *base
    command: black . --exclude=venv  
  
  types:
    <<: *base
    command: mypy . 

  postgress_bd:
    image: postgres:14
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/db
    ports:
      - '5432:5432'
    stdin_open: true
    tty: true
  
  redis:
    image: redis:7.0.8-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  pgdata:
  redis_data: