name: aiohttp_simple_server
on: [push]
jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: make lint
      - name: types
        run: make types